const YES_NO = [
  { id: "si", label: "Sí" },
  { id: "no", label: "No" },
];

function bool(spec) {
  return {
    code: spec.code,
    title: spec.title,
    description: spec.description ?? "Se corrige con el marcador final.",
    category: spec.category,
    difficulty: spec.difficulty,
    points: spec.points,
    answerType: "boolean",
    options: YES_NO,
    scoringRule: spec.rule,
    requiredFacts: ["home_score", "away_score"],
    active: spec.active !== false,
    priority: spec.priority ?? 0,
    cooldownDays: spec.cooldown ?? 2,
    tags: spec.tags ?? [spec.category],
  };
}

function buckets(spec) {
  return {
    code: spec.code,
    title: spec.title,
    description: spec.description ?? "Elige el rango. Se corrige con el marcador final.",
    category: spec.category,
    difficulty: spec.difficulty,
    points: spec.points,
    answerType: "multiple",
    options: spec.buckets.map((bucket) => ({ id: bucket.id, label: bucket.label })),
    scoringRule: { op: "buckets", fact: spec.fact, buckets: spec.buckets },
    requiredFacts: ["home_score", "away_score"],
    active: true,
    priority: spec.priority ?? 1,
    cooldownDays: 2,
    tags: spec.tags ?? [spec.category, "rango"],
  };
}

const and = (rules) => ({ op: "and", rules });

export const BANK = [
  bool({ code: "TOTAL_GTE_7", title: "¿Habrá 7 o más carreras en total?", category: "total", difficulty: "easy", points: 2, rule: { op: "total_gte", n: 7 } }),
  bool({ code: "TOTAL_GTE_8", title: "¿Habrá 8 o más carreras en total?", category: "total", difficulty: "easy", points: 2, rule: { op: "total_gte", n: 8 } }),
  bool({ code: "TOTAL_GTE_9", title: "¿Habrá 9 o más carreras en total?", category: "total", difficulty: "medium", points: 4, rule: { op: "total_gte", n: 9 } }),
  bool({ code: "TOTAL_GTE_10", title: "¿Habrá 10 o más carreras en total?", category: "total", difficulty: "medium", points: 4, rule: { op: "total_gte", n: 10 } }),
  bool({ code: "TOTAL_GTE_11", title: "¿Se irán a 11 o más carreras?", category: "total", difficulty: "hard", points: 6, rule: { op: "total_gte", n: 11 } }),
  bool({ code: "TOTAL_GTE_12", title: "¿Habrá 12 o más carreras en total?", category: "total", difficulty: "hard", points: 6, rule: { op: "total_gte", n: 12 } }),
  bool({ code: "TOTAL_GTE_13", title: "¿Habrá 13 o más carreras en total?", category: "total", difficulty: "expert", points: 8, rule: { op: "total_gte", n: 13 } }),
  bool({ code: "TOTAL_GTE_14", title: "¿Habrá 14 o más carreras en total?", category: "total", difficulty: "expert", points: 10, rule: { op: "total_gte", n: 14 } }),
  bool({ code: "TOTAL_GTE_15", title: "¿Habrá 15 o más carreras en total?", category: "total", difficulty: "expert", points: 10, rule: { op: "total_gte", n: 15 } }),
  bool({ code: "TOTAL_LTE_5", title: "¿El partido se queda en 5 carreras o menos?", category: "total", difficulty: "hard", points: 6, rule: { op: "total_lte", n: 5 } }),
  bool({ code: "TOTAL_LTE_6", title: "¿Habrá 6 o menos carreras en total?", category: "total", difficulty: "medium", points: 4, rule: { op: "total_lte", n: 6 } }),
  bool({ code: "TOTAL_LTE_7", title: "¿Habrá 7 o menos carreras en total?", category: "total", difficulty: "easy", points: 2, rule: { op: "total_lte", n: 7 } }),
  bool({ code: "TOTAL_LTE_8", title: "¿Habrá 8 o menos carreras en total?", category: "total", difficulty: "easy", points: 2, rule: { op: "total_lte", n: 8 } }),
  bool({ code: "TOTAL_LTE_9", title: "¿Se quedan en 9 carreras o menos?", category: "total", difficulty: "medium", points: 4, rule: { op: "total_lte", n: 9 } }),
  bool({ code: "TOTAL_EQ_6", title: "¿El total será exactamente 6 carreras?", category: "dificultad", difficulty: "expert", points: 10, rule: { op: "total_eq", n: 6 } }),
  bool({ code: "TOTAL_EQ_7", title: "¿El total será exactamente 7 carreras?", category: "dificultad", difficulty: "expert", points: 10, rule: { op: "total_eq", n: 7 } }),
  bool({ code: "TOTAL_EQ_8", title: "¿El total será exactamente 8 carreras?", category: "dificultad", difficulty: "expert", points: 10, rule: { op: "total_eq", n: 8 } }),
  bool({ code: "TOTAL_EQ_9", title: "¿El total será exactamente 9 carreras?", category: "dificultad", difficulty: "expert", points: 8, rule: { op: "total_eq", n: 9 } }),
  bool({ code: "TOTAL_EQ_10", title: "¿El total será exactamente 10 carreras?", category: "dificultad", difficulty: "expert", points: 8, rule: { op: "total_eq", n: 10 } }),
  bool({ code: "TOTAL_EQ_11", title: "¿El total será exactamente 11 carreras?", category: "dificultad", difficulty: "expert", points: 10, rule: { op: "total_eq", n: 11 } }),
  bool({ code: "TOTAL_EQ_12", title: "¿El total será exactamente 12 carreras?", category: "dificultad", difficulty: "expert", points: 10, rule: { op: "total_eq", n: 12 } }),
  bool({ code: "PARITY_EVEN", title: "¿El total de carreras será un número par?", category: "total", difficulty: "easy", points: 2, rule: { op: "parity", even: true } }),
  bool({ code: "PARITY_ODD", title: "¿El total de carreras será un número impar?", category: "total", difficulty: "easy", points: 2, rule: { op: "parity", even: false } }),
  buckets({
    code: "TOTAL_BUCKET_A",
    title: "¿En qué rango cae el total de carreras?",
    category: "total",
    difficulty: "medium",
    points: 4,
    fact: "total",
    buckets: [
      { id: "lt6", label: "Menos de 6", min: 0, max: 5 },
      { id: "6a8", label: "6 a 8", min: 6, max: 8 },
      { id: "9a11", label: "9 a 11", min: 9, max: 11 },
      { id: "12p", label: "12 o más", min: 12, max: null },
    ],
  }),
  buckets({
    code: "TOTAL_BUCKET_B",
    title: "¿Cuántas carreras suma el partido?",
    category: "total",
    difficulty: "hard",
    points: 6,
    fact: "total",
    buckets: [
      { id: "0a4", label: "0 a 4", min: 0, max: 4 },
      { id: "5a7", label: "5 a 7", min: 5, max: 7 },
      { id: "8a10", label: "8 a 10", min: 8, max: 10 },
      { id: "11p", label: "11 o más", min: 11, max: null },
    ],
  }),
  buckets({
    code: "TOTAL_BUCKET_C",
    title: "¿Dónde queda la suma de carreras?",
    category: "total",
    difficulty: "medium",
    points: 4,
    fact: "total",
    buckets: [
      { id: "lt8", label: "Menos de 8", min: 0, max: 7 },
      { id: "8a10", label: "8 a 10", min: 8, max: 10 },
      { id: "11a13", label: "11 a 13", min: 11, max: 13 },
      { id: "14p", label: "14 o más", min: 14, max: null },
    ],
  }),
  buckets({
    code: "TOTAL_BUCKET_D",
    title: "¿Qué tan cargado queda el marcador?",
    category: "marcador",
    difficulty: "hard",
    points: 6,
    fact: "total",
    buckets: [
      { id: "0a6", label: "0 a 6", min: 0, max: 6 },
      { id: "7a9", label: "7 a 9", min: 7, max: 9 },
      { id: "10a12", label: "10 a 12", min: 10, max: 12 },
      { id: "13p", label: "13 o más", min: 13, max: null },
    ],
  }),
  bool({ code: "MARGIN_EQ_1", title: "¿El ganador se impondrá por una carrera?", category: "cerrado", difficulty: "hard", points: 6, rule: { op: "margin_eq", n: 1 } }),
  bool({ code: "MARGIN_EQ_2", title: "¿La diferencia final será de exactamente 2?", category: "diferencia", difficulty: "expert", points: 8, rule: { op: "margin_eq", n: 2 } }),
  bool({ code: "MARGIN_EQ_3", title: "¿La diferencia final será de exactamente 3?", category: "diferencia", difficulty: "expert", points: 8, rule: { op: "margin_eq", n: 3 } }),
  bool({ code: "MARGIN_EQ_4", title: "¿La diferencia final será de exactamente 4?", category: "diferencia", difficulty: "expert", points: 10, rule: { op: "margin_eq", n: 4 } }),
  bool({ code: "MARGIN_EQ_5", title: "¿La diferencia final será de exactamente 5?", category: "dificultad", difficulty: "expert", points: 10, rule: { op: "margin_eq", n: 5 } }),
  bool({ code: "MARGIN_GTE_2", title: "¿El ganador sacará al menos 2 de ventaja?", category: "diferencia", difficulty: "easy", points: 2, rule: { op: "margin_gte", n: 2 } }),
  bool({ code: "MARGIN_GTE_3", title: "¿El ganador tendrá ventaja de 3 o más?", category: "diferencia", difficulty: "medium", points: 4, rule: { op: "margin_gte", n: 3 } }),
  bool({ code: "MARGIN_GTE_4", title: "¿Habrá diferencia de 4 o más carreras?", category: "abierto", difficulty: "medium", points: 4, rule: { op: "margin_gte", n: 4 } }),
  bool({ code: "MARGIN_GTE_5", title: "¿La ventaja final será de 5 o más?", category: "abierto", difficulty: "hard", points: 6, rule: { op: "margin_gte", n: 5 } }),
  bool({ code: "MARGIN_GTE_6", title: "¿Alguien se irá con 6 o más de ventaja?", category: "abierto", difficulty: "hard", points: 6, rule: { op: "margin_gte", n: 6 } }),
  bool({ code: "MARGIN_GTE_7", title: "¿La diferencia llegará a 7 o más?", category: "abierto", difficulty: "expert", points: 8, rule: { op: "margin_gte", n: 7 } }),
  bool({ code: "MARGIN_GTE_8", title: "¿Habrá una ventaja de 8 o más carreras?", category: "abierto", difficulty: "expert", points: 10, rule: { op: "margin_gte", n: 8 } }),
  bool({ code: "MARGIN_LTE_2", title: "¿La diferencia final será de 2 o menos?", category: "cerrado", difficulty: "medium", points: 4, rule: { op: "margin_lte", n: 2 } }),
  bool({ code: "MARGIN_LTE_3", title: "¿La ventaja final será de 3 o menos?", category: "cerrado", difficulty: "easy", points: 2, rule: { op: "margin_lte", n: 3 } }),
  buckets({
    code: "MARGIN_BUCKET_A",
    title: "¿De cuánto será la diferencia final?",
    category: "diferencia",
    difficulty: "medium",
    points: 4,
    fact: "margin",
    buckets: [
      { id: "m1", label: "1 carrera", min: 1, max: 1 },
      { id: "m2", label: "2 carreras", min: 2, max: 2 },
      { id: "m3", label: "3 carreras", min: 3, max: 3 },
      { id: "m4", label: "4 o más", min: 4, max: null },
    ],
  }),
  buckets({
    code: "MARGIN_BUCKET_B",
    title: "¿Qué tan holgado queda el final?",
    category: "diferencia",
    difficulty: "hard",
    points: 6,
    fact: "margin",
    buckets: [
      { id: "1a2", label: "1 o 2", min: 1, max: 2 },
      { id: "3a4", label: "3 o 4", min: 3, max: 4 },
      { id: "5a6", label: "5 o 6", min: 5, max: 6 },
      { id: "7p", label: "7 o más", min: 7, max: null },
    ],
  }),
  bool({ code: "WINNER_GTE_4", title: "¿El ganador anotará 4 o más?", category: "resultado", difficulty: "easy", points: 2, rule: { op: "winner_gte", n: 4 } }),
  bool({ code: "WINNER_GTE_5", title: "¿El ganador anotará 5 o más?", category: "resultado", difficulty: "easy", points: 2, rule: { op: "winner_gte", n: 5 } }),
  bool({ code: "WINNER_GTE_6", title: "¿El ganador llegará a 6 o más?", category: "resultado", difficulty: "medium", points: 4, rule: { op: "winner_gte", n: 6 } }),
  bool({ code: "WINNER_GTE_7", title: "¿El ganador anotará 7 o más?", category: "resultado", difficulty: "hard", points: 6, rule: { op: "winner_gte", n: 7 } }),
  bool({ code: "WINNER_GTE_8", title: "¿El ganador llegará a 8 o más?", category: "resultado", difficulty: "expert", points: 8, rule: { op: "winner_gte", n: 8 } }),
  bool({ code: "WINNER_GTE_9", title: "¿El ganador anotará 9 o más?", category: "resultado", difficulty: "expert", points: 10, rule: { op: "winner_gte", n: 9 } }),
  bool({ code: "WINNER_LTE_3", title: "¿El ganador se quedará en 3 o menos?", category: "resultado", difficulty: "hard", points: 6, rule: { op: "winner_lte", n: 3 } }),
  bool({ code: "WINNER_LTE_4", title: "¿Al ganador le bastan 4 o menos?", category: "resultado", difficulty: "medium", points: 4, rule: { op: "winner_lte", n: 4 } }),
  buckets({
    code: "WINNER_BUCKET",
    title: "¿Cuántas anota el ganador?",
    category: "resultado",
    difficulty: "medium",
    points: 4,
    fact: "winner_runs",
    buckets: [
      { id: "1a3", label: "1 a 3", min: 1, max: 3 },
      { id: "4a6", label: "4 a 6", min: 4, max: 6 },
      { id: "7a9", label: "7 a 9", min: 7, max: 9 },
      { id: "10p", label: "10 o más", min: 10, max: null },
    ],
  }),
  bool({ code: "LOSER_LTE_1", title: "¿El perdedor se quedará en 1 o menos?", category: "defensiva", difficulty: "medium", points: 4, rule: { op: "loser_lte", n: 1 } }),
  bool({ code: "LOSER_LTE_2", title: "¿El perdedor anotará 2 o menos?", category: "defensiva", difficulty: "easy", points: 2, rule: { op: "loser_lte", n: 2 } }),
  bool({ code: "LOSER_LTE_3", title: "¿El perdedor se queda en 3 o menos?", category: "defensiva", difficulty: "easy", points: 2, rule: { op: "loser_lte", n: 3 } }),
  bool({ code: "LOSER_GTE_3", title: "¿El perdedor anotará 3 o más?", category: "marcador", difficulty: "medium", points: 4, rule: { op: "loser_gte", n: 3 } }),
  bool({ code: "LOSER_GTE_4", title: "¿El que pierda igual anota 4 o más?", category: "marcador", difficulty: "hard", points: 6, rule: { op: "loser_gte", n: 4 } }),
  bool({ code: "LOSER_GTE_5", title: "¿El perdedor llegará a 5 o más?", category: "ofensiva", difficulty: "expert", points: 8, rule: { op: "loser_gte", n: 5 } }),
  buckets({
    code: "LOSER_BUCKET",
    title: "¿Cuántas anota el perdedor?",
    category: "marcador",
    difficulty: "hard",
    points: 6,
    fact: "loser_runs",
    buckets: [
      { id: "0a1", label: "0 o 1", min: 0, max: 1 },
      { id: "2a3", label: "2 o 3", min: 2, max: 3 },
      { id: "4a5", label: "4 o 5", min: 4, max: 5 },
      { id: "6p", label: "6 o más", min: 6, max: null },
    ],
  }),
  bool({ code: "BOTH_GTE_1", title: "¿Los dos equipos van a anotar?", category: "marcador", difficulty: "easy", points: 2, rule: { op: "both_gte", n: 1 } }),
  bool({ code: "BOTH_GTE_2", title: "¿Ambos equipos anotarán al menos 2?", category: "ofensiva", difficulty: "easy", points: 2, rule: { op: "both_gte", n: 2 } }),
  bool({ code: "BOTH_GTE_3", title: "¿Ambos equipos anotarán al menos 3?", category: "ofensiva", difficulty: "medium", points: 4, rule: { op: "both_gte", n: 3 } }),
  bool({ code: "BOTH_GTE_4", title: "¿Ambos equipos llegarán a 4 o más?", category: "ofensiva", difficulty: "hard", points: 6, rule: { op: "both_gte", n: 4 } }),
  bool({ code: "BOTH_GTE_5", title: "¿Ambos equipos anotarán 5 o más?", category: "ofensiva", difficulty: "expert", points: 10, rule: { op: "both_gte", n: 5 } }),
  bool({ code: "BOTH_LTE_2", title: "¿Ningún equipo pasa de 2 carreras?", category: "defensiva", difficulty: "expert", points: 8, rule: { op: "both_lte", n: 2 } }),
  bool({ code: "BOTH_LTE_3", title: "¿Ningún equipo llega a 4 carreras?", category: "defensiva", difficulty: "hard", points: 6, rule: { op: "both_lte", n: 3 } }),
  bool({ code: "BOTH_LTE_4", title: "¿Ningún equipo anota más de 4?", category: "defensiva", difficulty: "medium", points: 4, rule: { op: "both_lte", n: 4 } }),
  bool({ code: "EITHER_GTE_5", title: "¿Algún equipo anotará 5 o más?", category: "ofensiva", difficulty: "easy", points: 2, rule: { op: "either_gte", n: 5 } }),
  bool({ code: "EITHER_GTE_6", title: "¿Algún equipo llegará a 6 o más?", category: "ofensiva", difficulty: "medium", points: 4, rule: { op: "either_gte", n: 6 } }),
  bool({ code: "EITHER_GTE_7", title: "¿Algún equipo anotará 7 o más?", category: "ofensiva", difficulty: "hard", points: 6, rule: { op: "either_gte", n: 7 } }),
  bool({ code: "EITHER_GTE_8", title: "¿Algún equipo llegará a 8 o más?", category: "ofensiva", difficulty: "expert", points: 8, rule: { op: "either_gte", n: 8 } }),
  bool({ code: "EITHER_GTE_9", title: "¿Algún equipo anotará 9 o más?", category: "ofensiva", difficulty: "expert", points: 10, rule: { op: "either_gte", n: 9 } }),
  bool({ code: "EITHER_GTE_10", title: "¿Algún equipo llegará a 10 carreras?", category: "ofensiva", difficulty: "expert", points: 10, rule: { op: "either_gte", n: 10 } }),
  bool({ code: "SHUTOUT", title: "¿Algún equipo terminará en cero?", category: "defensiva", difficulty: "hard", points: 6, rule: { op: "shutout" } }),
  bool({ code: "HOME_ZERO", title: "¿El local termina en cero?", category: "defensiva", difficulty: "expert", points: 8, rule: { op: "home_eq", n: 0 } }),
  bool({ code: "AWAY_ZERO", title: "¿El visitante termina en cero?", category: "defensiva", difficulty: "expert", points: 8, rule: { op: "away_eq", n: 0 } }),
  bool({ code: "HOME_GTE_2", title: "¿El local anota al menos 2?", category: "marcador", difficulty: "easy", points: 2, rule: { op: "home_gte", n: 2 } }),
  bool({ code: "HOME_GTE_3", title: "¿El local anota 3 o más?", category: "marcador", difficulty: "easy", points: 2, rule: { op: "home_gte", n: 3 } }),
  bool({ code: "HOME_GTE_4", title: "¿El local anota 4 o más?", category: "marcador", difficulty: "medium", points: 4, rule: { op: "home_gte", n: 4 } }),
  bool({ code: "HOME_GTE_5", title: "¿El local llega a 5 o más?", category: "marcador", difficulty: "medium", points: 4, rule: { op: "home_gte", n: 5 } }),
  bool({ code: "HOME_GTE_6", title: "¿El local anota 6 o más?", category: "ofensiva", difficulty: "hard", points: 6, rule: { op: "home_gte", n: 6 } }),
  bool({ code: "HOME_GTE_7", title: "¿El local llega a 7 o más?", category: "ofensiva", difficulty: "expert", points: 8, rule: { op: "home_gte", n: 7 } }),
  bool({ code: "HOME_LTE_2", title: "¿El local se queda en 2 o menos?", category: "defensiva", difficulty: "medium", points: 4, rule: { op: "home_lte", n: 2 } }),
  bool({ code: "HOME_LTE_3", title: "¿El local anota 3 o menos?", category: "defensiva", difficulty: "easy", points: 2, rule: { op: "home_lte", n: 3 } }),
  bool({ code: "AWAY_GTE_2", title: "¿El visitante anota al menos 2?", category: "marcador", difficulty: "easy", points: 2, rule: { op: "away_gte", n: 2 } }),
  bool({ code: "AWAY_GTE_3", title: "¿El visitante anota 3 o más?", category: "marcador", difficulty: "easy", points: 2, rule: { op: "away_gte", n: 3 } }),
  bool({ code: "AWAY_GTE_4", title: "¿El visitante anota 4 o más?", category: "marcador", difficulty: "medium", points: 4, rule: { op: "away_gte", n: 4 } }),
  bool({ code: "AWAY_GTE_5", title: "¿El visitante llega a 5 o más?", category: "marcador", difficulty: "medium", points: 4, rule: { op: "away_gte", n: 5 } }),
  bool({ code: "AWAY_GTE_6", title: "¿El visitante anota 6 o más?", category: "ofensiva", difficulty: "hard", points: 6, rule: { op: "away_gte", n: 6 } }),
  bool({ code: "AWAY_GTE_7", title: "¿El visitante llega a 7 o más?", category: "ofensiva", difficulty: "expert", points: 8, rule: { op: "away_gte", n: 7 } }),
  bool({ code: "AWAY_LTE_2", title: "¿El visitante se queda en 2 o menos?", category: "defensiva", difficulty: "medium", points: 4, rule: { op: "away_lte", n: 2 } }),
  bool({ code: "AWAY_LTE_3", title: "¿El visitante anota 3 o menos?", category: "defensiva", difficulty: "easy", points: 2, rule: { op: "away_lte", n: 3 } }),
  buckets({
    code: "HOME_BUCKET",
    title: "¿Cuántas anota el local?",
    category: "marcador",
    difficulty: "medium",
    points: 4,
    fact: "home",
    buckets: [
      { id: "0a2", label: "0 a 2", min: 0, max: 2 },
      { id: "3a5", label: "3 a 5", min: 3, max: 5 },
      { id: "6a8", label: "6 a 8", min: 6, max: 8 },
      { id: "9p", label: "9 o más", min: 9, max: null },
    ],
  }),
  buckets({
    code: "AWAY_BUCKET",
    title: "¿Cuántas anota el visitante?",
    category: "marcador",
    difficulty: "medium",
    points: 4,
    fact: "away",
    buckets: [
      { id: "0a2", label: "0 a 2", min: 0, max: 2 },
      { id: "3a5", label: "3 a 5", min: 3, max: 5 },
      { id: "6a8", label: "6 a 8", min: 6, max: 8 },
      { id: "9p", label: "9 o más", min: 9, max: null },
    ],
  }),
  bool({
    code: "CLOSED_BUSY",
    title: "¿Habrá 8 o más carreras y diferencia de una?",
    category: "cerrado",
    difficulty: "expert",
    points: 10,
    rule: and([{ op: "total_gte", n: 8 }, { op: "margin_eq", n: 1 }]),
  }),
  bool({
    code: "CLOSED_BOTH3",
    title: "¿Ambos anotan 3 o más y la diferencia es de 2 o menos?",
    category: "cerrado",
    difficulty: "hard",
    points: 6,
    rule: and([{ op: "both_gte", n: 3 }, { op: "margin_lte", n: 2 }]),
  }),
  bool({
    code: "ONE_RUN_BOTH",
    title: "¿Los dos anotan y el final se decide por una?",
    category: "cerrado",
    difficulty: "expert",
    points: 8,
    rule: and([{ op: "both_gte", n: 1 }, { op: "margin_eq", n: 1 }]),
  }),
  bool({
    code: "CLOSED_HIGH",
    title: "¿Habrá 9 o más carreras con diferencia de 3 o menos?",
    category: "cerrado",
    difficulty: "medium",
    points: 4,
    rule: and([{ op: "total_gte", n: 9 }, { op: "margin_lte", n: 3 }]),
  }),
  bool({
    code: "OPEN_WINNER7",
    title: "¿El ganador llega a 7 con ventaja de 4 o más?",
    category: "abierto",
    difficulty: "expert",
    points: 8,
    rule: and([{ op: "winner_gte", n: 7 }, { op: "margin_gte", n: 4 }]),
  }),
  bool({
    code: "DOUBLES",
    title: "¿El ganador le dobla las carreras al perdedor?",
    category: "abierto",
    difficulty: "hard",
    points: 6,
    rule: { op: "winner_doubles" },
    description: "El perdedor anota al menos una y el ganador llega al doble.",
  }),
  bool({
    code: "OPEN_QUIET_LOSER",
    title: "¿Habrá ventaja de 3 o más y el perdedor en 2 o menos?",
    category: "abierto",
    difficulty: "medium",
    points: 4,
    rule: and([{ op: "margin_gte", n: 3 }, { op: "loser_lte", n: 2 }]),
  }),
  bool({
    code: "SHUTOUT_FIVE",
    title: "¿Habrá blanqueada y el ganador anota 5 o más?",
    category: "defensiva",
    difficulty: "expert",
    points: 10,
    rule: and([{ op: "shutout" }, { op: "winner_gte", n: 5 }]),
  }),
  bool({
    code: "OFFENSE_BOTH4_CLOSE",
    title: "¿Ambos llegan a 4 y el partido no se abre a más de 2?",
    category: "ofensiva",
    difficulty: "expert",
    points: 8,
    rule: and([{ op: "both_gte", n: 4 }, { op: "margin_lte", n: 2 }]),
  }),
  bool({
    code: "LOW_AND_CLOSE",
    title: "¿Habrá 6 o menos carreras y diferencia de 2 o menos?",
    category: "defensiva",
    difficulty: "hard",
    points: 6,
    rule: and([{ op: "total_lte", n: 6 }, { op: "margin_lte", n: 2 }]),
  }),
  bool({
    code: "HOME_BURST",
    title: "¿El local anota 6 o más y el visitante se queda en 3 o menos?",
    category: "resultado",
    difficulty: "expert",
    points: 8,
    rule: and([{ op: "home_gte", n: 6 }, { op: "away_lte", n: 3 }]),
  }),
  bool({
    code: "AWAY_BURST",
    title: "¿El visitante anota 6 o más y el local se queda en 3 o menos?",
    category: "resultado",
    difficulty: "expert",
    points: 8,
    rule: and([{ op: "away_gte", n: 6 }, { op: "home_lte", n: 3 }]),
  }),
  bool({
    code: "HOME_EXACT_3",
    title: "¿El local anota exactamente 3?",
    category: "dificultad",
    difficulty: "expert",
    points: 8,
    rule: { op: "home_eq", n: 3 },
  }),
  bool({
    code: "AWAY_EXACT_3",
    title: "¿El visitante anota exactamente 3?",
    category: "dificultad",
    difficulty: "expert",
    points: 8,
    rule: { op: "away_eq", n: 3 },
  }),
  bool({
    code: "HOME_EXACT_4",
    title: "¿El local anota exactamente 4?",
    category: "dificultad",
    difficulty: "expert",
    points: 10,
    rule: { op: "home_eq", n: 4 },
  }),
  bool({
    code: "AWAY_EXACT_4",
    title: "¿El visitante anota exactamente 4?",
    category: "dificultad",
    difficulty: "expert",
    points: 10,
    rule: { op: "away_eq", n: 4 },
  }),
  bool({
    code: "HOME_EXACT_5",
    title: "¿El local anota exactamente 5?",
    category: "dificultad",
    difficulty: "expert",
    points: 10,
    rule: { op: "home_eq", n: 5 },
  }),
  bool({
    code: "AWAY_EXACT_5",
    title: "¿El visitante anota exactamente 5?",
    category: "dificultad",
    difficulty: "expert",
    points: 10,
    rule: { op: "away_eq", n: 5 },
  }),
  bool({
    code: "TEN_PLUS_CLOSE",
    title: "¿Habrá 10 o más carreras con diferencia de 2 o menos?",
    category: "total",
    difficulty: "expert",
    points: 8,
    rule: and([{ op: "total_gte", n: 10 }, { op: "margin_lte", n: 2 }]),
  }),
  bool({
    code: "FIVE_EACH_SIDE",
    title: "¿Los dos equipos llegan al menos a 4 y el total pasa de 9?",
    category: "ofensiva",
    difficulty: "hard",
    points: 6,
    rule: and([{ op: "both_gte", n: 4 }, { op: "total_gte", n: 10 }]),
  }),
  bool({
    code: "WINNER_EXACT_DOUBLE",
    title: "¿El perdedor anota 3 o más y el ganador le dobla?",
    category: "dificultad",
    difficulty: "expert",
    points: 10,
    rule: and([{ op: "loser_gte", n: 3 }, { op: "winner_doubles" }, { op: "margin_gte", n: 3 }]),
  }),
  bool({ code: "MARGIN_EQ_6", title: "¿La diferencia final será de exactamente 6?", category: "diferencia", difficulty: "expert", points: 10, rule: { op: "margin_eq", n: 6 } }),
  bool({ code: "TOTAL_GTE_16", title: "¿Habrá 16 o más carreras en total?", category: "total", difficulty: "expert", points: 10, rule: { op: "total_gte", n: 16 } }),
  bool({ code: "BOTH_GTE_6", title: "¿Ambos equipos anotarán 6 o más?", category: "ofensiva", difficulty: "expert", points: 10, rule: { op: "both_gte", n: 6 } }),
  bool({ code: "LOSER_GTE_6", title: "¿Hasta el perdedor anota 6 o más?", category: "ofensiva", difficulty: "expert", points: 10, rule: { op: "loser_gte", n: 6 } }),
  bool({ code: "HOME_GTE_8", title: "¿El local llega a 8 o más?", category: "resultado", difficulty: "expert", points: 8, rule: { op: "home_gte", n: 8 } }),
  bool({ code: "AWAY_GTE_8", title: "¿El visitante llega a 8 o más?", category: "resultado", difficulty: "expert", points: 8, rule: { op: "away_gte", n: 8 } }),
  bool({ code: "TOTAL_LTE_4", title: "¿El partido se queda en 4 carreras o menos?", category: "defensiva", difficulty: "expert", points: 10, rule: { op: "total_lte", n: 4 } }),
  bool({ code: "EITHER_GTE_4", title: "¿Algún equipo anota 4 o más?", category: "ofensiva", difficulty: "easy", points: 2, rule: { op: "either_gte", n: 4 } }),
  bool({ code: "WINNER_GTE_10", title: "¿El ganador llega a 10 o más?", category: "resultado", difficulty: "expert", points: 10, rule: { op: "winner_gte", n: 10 } }),
  bool({ code: "MARGIN_LTE_4", title: "¿La diferencia se queda en 4 o menos?", category: "diferencia", difficulty: "easy", points: 2, rule: { op: "margin_lte", n: 4 } }),
];
